### ISSUE TITLE
Compiling functionality not working

### ISSUE THREAD

**Issue by mdjacksparrow** [KrishnaMoorthy12/trident#12] opened 2019-12-10 04:00 UTC
This software is good but the compiler and run functionality lead to a crash or may not be working properly ! when I'm compiled only an exception is thrown not give my output.
So kindly fixed it!

**Comment by krissh-codes** [comment] 2019-12-10 05:59
**Probably not a bug**
Trident can compile only Python and Java source files for now. Currently, Trident does not support using any kind of input statements to be used in your program (while running). Sorry for any inconvenience caused. Any errors/ output are redirected to "<your file name>-output.txt". Please confirm the above. Also, I request you to share information about the Exception that is thrown (details from the Error Message Dialog, including ERROR NAME, CODE and CAUSE). 
Looking forward to fixing it, if in case it is a bug. Thanks for reporting your issue at GitHub. I appreciate your positive intent.

**Comment by krissh-codes** [comment] 2019-12-10 17:41
Bug was spotted  and fixed in latest release v1.2 - thanks for your report. 
Commit - ea504f27564c9dcf337435480b768f45ae54acff

**Closed as completed by krissh-codes** 2019-12-10 17:41 UTC
Labels: bug, good first issue, question
